### PR TITLE
Remove pgtkconn, we no longer need it

### PR DESCRIPTION
**Pull request by fejfighter**
I had suspicions that this could be removed, it mostly relates to X11 rendering.

in this form Emacs becomes a glorified GTK3 widget, where gtk handles connections to the window-manager/compositor/whatever.

Less code means less to worry about

### CODE REVIEW

**Comment by masm11** [comment]
pgtkconn has nothing to do with X11 rendering.

In the past,
I needed SIGIO to interrupt with C-g while emacs was busy.
I needed the file descriptor of the connection to call `init_sigio()`.

I didn't like pgtkconn because it was ugly.

Afterward,
I implemented hourglass using atimer.

The hourglass handler is called periodically, and keyboard events are handled at that moment,
so I can interrupt busy emacs.
I don't need pgtkconn now.

Could you remove `int connection;` in `struct pgtk_display_info` defined in pgtkterm.h
to ensure it is no longer used?

> Less code means less to worry about

Yes, I know.

**Comment by fejfighter** [comment]
I figured it was part of early stages of the port,
but no longer necessary.

I think I got the rendering idea from 
https://www.facebook.com/notes/daniel-colascione/buttery-smooth-emacs/10155313440066102 
which talks about using it for redisplay.

I have removed `int connection`, I forgot the display info `struct` was per windowing type and not shared like frame.

**Comment by masm11** [comment]
Thank you!

**Comment by masm11** [comment]
@fejfighter 
You may be aware, but text cursor blinking is not stable after merging this PR.
Can you debug that?
I'm also debugging.

**Comment by fejfighter** [comment]
@masm11 
now that you mention it, I have now noticed.
I was pulled away from that code yesterday.

I'll debug today.

should this be reverted until it's fixed?

**Pull request merged**
