### PR TITLE
Add a Gentoo ebuild

### PR DESCRIPTION
**Pull request by vozhyk-**
I use it to install this version of Emacs on my system.

### CODE REVIEW

**Comment by masm11** [comment]
Thanks.

**Comment by masm11** [comment]
@vozhyk- 
Hi,

I want to merge this fork to mainline.

Since I need to assign copyright of my code in this fork to FSF, I'm doing.

This fork contains your code.
You need to assign copyright of your code in this fork to FSF.
Do you agree?
If you agree, please email to emacs-devel@gnu.org and ask for the copyright
assignment form to get the process started.
Otherwise, tell me, then I'll revert your PR.

**Comment by vozhyk-** [comment]
I don't think the ebuilds need to be included in mainline Emacs code, so reverting this is fine.

I've only added them here to make it convenient for others to install this fork. If this fork gets mainlined, then users can just install Emacs releases using the official https://github.com/gentoo/gentoo repository.

**Comment by masm11** [comment]
Thank you for your response.
OK, I reverted.

**Pull request merged**
